### ISSUE TITLE
how to detect usb keyboard or mouse plugin

### ISSUE THREAD

**Issue by rickywu** [jNizM/ahk-scripts-v2#3]
I tried WM_DEVICECHANGE works for usb storage device, but not work for usb keyboard and mouse

I use msgbox print wparam got 7, how to set these value?

**Comment by jNizM** [comment]
For all USB-Devices you should use "RegisterDeviceNotification" or try example 2 from here https://www.autohotkey.com/boards/viewtopic.php?t=105171
